/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccessStatsPanel: typeof import('./src/components/security/AccessStatsPanel.vue')['default']
    AlarmCard: typeof import('./src/components/common/AlarmCard.vue')['default']
    AlarmDetailView: typeof import('./src/components/common/AlarmDetailView.vue')['default']
    AlarmListItem: typeof import('./src/components/common/AlarmListItem.vue')['default']
    AlarmListPanel: typeof import('./src/components/security/AlarmListPanel.vue')['default']
    AlarmTrendPanel: typeof import('./src/components/security/AlarmTrendPanel.vue')['default']
    AppButton: typeof import('./src/components/common/AppButton.vue')['default']
    AppErrorBoundary: typeof import('./src/components/AppErrorBoundary.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    BaseMap: typeof import('./src/components/cesium/BaseMap.vue')['default']
    BottomMessageBar: typeof import('./src/components/common/BottomMessageBar.vue')['default']
    ClosedCasePanel: typeof import('./src/components/dashboard/ClosedCasePanel.vue')['default']
    DutyPanel: typeof import('./src/components/dashboard/DutyPanel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    EmergencyEventCrudPanel: typeof import('./src/components/dashboard/EmergencyEventCrudPanel.vue')['default']
    EmergencyKnowledgePanel: typeof import('./src/components/dashboard/EmergencyKnowledgePanel.vue')['default']
    EmergencyPhonePanel: typeof import('./src/components/dashboard/EmergencyPhonePanel.vue')['default']
    EmergencyStrengthPanel: typeof import('./src/components/dashboard/EmergencyStrengthPanel.vue')['default']
    EventAnalysisPanel: typeof import('./src/components/industrial-video/EventAnalysisPanel.vue')['default']
    FactoryInspectionPanel: typeof import('./src/components/industrial-video/FactoryInspectionPanel.vue')['default']
    FireAlarmPanel: typeof import('./src/components/fire/FireAlarmPanel.vue')['default']
    FireDevicePanel: typeof import('./src/components/fire/FireDevicePanel.vue')['default']
    FireFacilityPanel: typeof import('./src/components/fire/FireFacilityPanel.vue')['default']
    FireStrengthPanel: typeof import('./src/components/fire/FireStrengthPanel.vue')['default']
    GaugeChart: typeof import('./src/components/charts/GaugeChart.vue')['default']
    LineChart: typeof import('./src/components/charts/LineChart.vue')['default']
    LinkPatrolPanel: typeof import('./src/components/security/LinkPatrolPanel.vue')['default']
    MaintenanceOrderPanel: typeof import('./src/components/industrial-video/MaintenanceOrderPanel.vue')['default']
    MapBottomTools: typeof import('./src/components/map/MapBottomTools.vue')['default']
    MapClusterPopup: typeof import('./src/components/cesium/MapClusterPopup.vue')['default']
    MapDetailPanel: typeof import('./src/components/cesium/MapDetailPanel.vue')['default']
    MapFloatTools: typeof import('./src/components/map/MapFloatTools.vue')['default']
    MapPin: typeof import('./src/components/common/MapPin.vue')['default']
    ModuleLayout: typeof import('./src/components/layout/ModuleLayout.vue')['default']
    MonitorDialog: typeof import('./src/components/common/MonitorDialog.vue')['default']
    PanelCard: typeof import('./src/components/common/PanelCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryPageOverlay: typeof import('./src/components/common/SecondaryPageOverlay.vue')['default']
    SpecialWorkPanel: typeof import('./src/components/fire/SpecialWorkPanel.vue')['default']
    StatCard: typeof import('./src/components/common/StatCard.vue')['default']
    SystemNoticeBar: typeof import('./src/components/industrial-video/SystemNoticeBar.vue')['default']
    VideoAnalysisPanel: typeof import('./src/components/industrial-video/VideoAnalysisPanel.vue')['default']
    VideoOverviewPanel: typeof import('./src/components/industrial-video/VideoOverviewPanel.vue')['default']
    VideoPatrolPanel: typeof import('./src/components/industrial-video/VideoPatrolPanel.vue')['default']
  }
}
