/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlarmCard: typeof import('./src/components/common/AlarmCard.vue')['default']
    AlarmListItem: typeof import('./src/components/common/AlarmListItem.vue')['default']
    AppButton: typeof import('./src/components/common/AppButton.vue')['default']
    AppErrorBoundary: typeof import('./src/components/AppErrorBoundary.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    BaseMap: typeof import('./src/components/cesium/BaseMap.vue')['default']
    BottomMessageBar: typeof import('./src/components/common/BottomMessageBar.vue')['default']
    ClosedCasePanel: typeof import('./src/components/dashboard/ClosedCasePanel.vue')['default']
    DutyPanel: typeof import('./src/components/dashboard/DutyPanel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    EmergencyEventCrudPanel: typeof import('./src/components/dashboard/EmergencyEventCrudPanel.vue')['default']
    EmergencyKnowledgePanel: typeof import('./src/components/dashboard/EmergencyKnowledgePanel.vue')['default']
    EmergencyPhonePanel: typeof import('./src/components/dashboard/EmergencyPhonePanel.vue')['default']
    EmergencyStrengthPanel: typeof import('./src/components/dashboard/EmergencyStrengthPanel.vue')['default']
    MapPin: typeof import('./src/components/common/MapPin.vue')['default']
    ModuleLayout: typeof import('./src/components/layout/ModuleLayout.vue')['default']
    PanelCard: typeof import('./src/components/common/PanelCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryPageOverlay: typeof import('./src/components/common/SecondaryPageOverlay.vue')['default']
    StatCard: typeof import('./src/components/common/StatCard.vue')['default']
  }
}
